# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab4.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1030, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1030, 650))
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelArticle = QtWidgets.QLabel(self.centralwidget)
        self.labelArticle.setGeometry(QtCore.QRect(10, 45, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelArticle.setFont(font)
        self.labelArticle.setObjectName("labelArticle")
        self.editArticle = QtWidgets.QLineEdit(self.centralwidget)
        self.editArticle.setGeometry(QtCore.QRect(100, 50, 150, 20))
        self.editArticle.setObjectName("editArticle")
        self.labelProducer = QtWidgets.QLabel(self.centralwidget)
        self.labelProducer.setGeometry(QtCore.QRect(10, 75, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelProducer.setFont(font)
        self.labelProducer.setObjectName("labelProducer")
        self.editProducer = QtWidgets.QLineEdit(self.centralwidget)
        self.editProducer.setGeometry(QtCore.QRect(100, 80, 150, 20))
        self.editProducer.setObjectName("editProducer")
        self.labelCores = QtWidgets.QLabel(self.centralwidget)
        self.labelCores.setGeometry(QtCore.QRect(10, 135, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCores.setFont(font)
        self.labelCores.setObjectName("labelCores")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(10, 105, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.labelPrice = QtWidgets.QLabel(self.centralwidget)
        self.labelPrice.setGeometry(QtCore.QRect(10, 195, 45, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPrice.setFont(font)
        self.labelPrice.setObjectName("labelPrice")
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setGeometry(QtCore.QRect(100, 110, 150, 20))
        self.editName.setObjectName("editName")
        self.editCores = QtWidgets.QLineEdit(self.centralwidget)
        self.editCores.setGeometry(QtCore.QRect(100, 140, 150, 20))
        self.editCores.setObjectName("editCores")
        self.editPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.editPrice.setGeometry(QtCore.QRect(100, 200, 150, 20))
        self.editPrice.setObjectName("editPrice")
        self.buttonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAdd.setGeometry(QtCore.QRect(60, 250, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonAdd.setFont(font)
        self.buttonAdd.setObjectName("buttonAdd")
        self.labelAdd = QtWidgets.QLabel(self.centralwidget)
        self.labelAdd.setGeometry(QtCore.QRect(80, 5, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelAdd.setFont(font)
        self.labelAdd.setObjectName("labelAdd")
        self.labelDelete = QtWidgets.QLabel(self.centralwidget)
        self.labelDelete.setGeometry(QtCore.QRect(300, 5, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDelete.setFont(font)
        self.labelDelete.setObjectName("labelDelete")
        self.labelDeleteInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelDeleteInfo.setGeometry(QtCore.QRect(300, 40, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDeleteInfo.setFont(font)
        self.labelDeleteInfo.setObjectName("labelDeleteInfo")
        self.editDeleteArticle = QtWidgets.QLineEdit(self.centralwidget)
        self.editDeleteArticle.setGeometry(QtCore.QRect(580, 45, 150, 20))
        self.editDeleteArticle.setObjectName("editDeleteArticle")
        self.buttonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDelete.setGeometry(QtCore.QRect(750, 40, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonDelete.setFont(font)
        self.buttonDelete.setObjectName("buttonDelete")
        self.labelSearch = QtWidgets.QLabel(self.centralwidget)
        self.labelSearch.setGeometry(QtCore.QRect(300, 100, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelSearch.setFont(font)
        self.labelSearch.setObjectName("labelSearch")
        self.labelSearchInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelSearchInfo.setGeometry(QtCore.QRect(300, 130, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelSearchInfo.setFont(font)
        self.labelSearchInfo.setObjectName("labelSearchInfo")
        self.editSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.editSearch.setGeometry(QtCore.QRect(610, 135, 150, 20))
        self.editSearch.setObjectName("editSearch")
        self.buttonSearch = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSearch.setGeometry(QtCore.QRect(770, 130, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonSearch.setFont(font)
        self.buttonSearch.setObjectName("buttonSearch")
        self.tableResult = QtWidgets.QTableWidget(self.centralwidget)
        self.tableResult.setGeometry(QtCore.QRect(0, 310, 1011, 311))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableResult.setFont(font)
        self.tableResult.setObjectName("tableResult")
        self.tableResult.setColumnCount(0)
        self.tableResult.setRowCount(0)
        self.labelFrequency = QtWidgets.QLabel(self.centralwidget)
        self.labelFrequency.setGeometry(QtCore.QRect(10, 165, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelFrequency.setFont(font)
        self.labelFrequency.setObjectName("labelFrequency")
        self.editFrequency = QtWidgets.QLineEdit(self.centralwidget)
        self.editFrequency.setGeometry(QtCore.QRect(100, 170, 150, 20))
        self.editFrequency.setObjectName("editFrequency")
        self.buttonPrintAll = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPrintAll.setGeometry(QtCore.QRect(300, 190, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonPrintAll.setFont(font)
        self.buttonPrintAll.setObjectName("buttonPrintAll")
        self.comboBoxCores = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCores.setGeometry(QtCore.QRect(470, 190, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBoxCores.setFont(font)
        self.comboBoxCores.setObjectName("comboBoxCores")
        self.checkBoxPrice = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxPrice.setGeometry(QtCore.QRect(610, 190, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBoxPrice.setFont(font)
        self.checkBoxPrice.setObjectName("checkBoxPrice")
        self.buttonPrintByCheckBox = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPrintByCheckBox.setGeometry(QtCore.QRect(470, 240, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonPrintByCheckBox.setFont(font)
        self.buttonPrintByCheckBox.setObjectName("buttonPrintByCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Processors"))
        self.labelArticle.setText(_translate("MainWindow", "Article:"))
        self.labelProducer.setText(_translate("MainWindow", "Producer:"))
        self.labelCores.setText(_translate("MainWindow", "Cores:"))
        self.labelName.setText(_translate("MainWindow", "Name:"))
        self.labelPrice.setText(_translate("MainWindow", "Price:"))
        self.buttonAdd.setText(_translate("MainWindow", "Add"))
        self.labelAdd.setText(_translate("MainWindow", "Add"))
        self.labelDelete.setText(_translate("MainWindow", "Delete:"))
        self.labelDeleteInfo.setText(_translate("MainWindow", "Write processor`s article to delete:"))
        self.buttonDelete.setText(_translate("MainWindow", "Delete"))
        self.labelSearch.setText(_translate("MainWindow", "Search:"))
        self.labelSearchInfo.setText(_translate("MainWindow", "Write processor`s producer to search:"))
        self.buttonSearch.setText(_translate("MainWindow", "Search"))
        self.labelFrequency.setText(_translate("MainWindow", "Frequency:"))
        self.buttonPrintAll.setText(_translate("MainWindow", "Print all"))
        self.checkBoxPrice.setText(_translate("MainWindow", "Price > 100?"))
        self.buttonPrintByCheckBox.setText(_translate("MainWindow", "Print Cores"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
