-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 10:38:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Статус проекта`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Статус проекта` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Статус проекта` (
  `Код статуса проекта` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код статуса проекта`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Проект`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Проект` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Проект` (
  `Код проекта` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(100) NOT NULL,
  `Краткое название` VARCHAR(45) NOT NULL,
  `Краткое описание` LONGTEXT NOT NULL,
  `Дата начала` DATE NOT NULL,
  `Дата окончания` DATE NOT NULL,
  `Статус проекта_Код статуса проекта` INT NOT NULL,
  PRIMARY KEY (`Код проекта`),
  INDEX `fk_Проект_Статус проекта1_idx` (`Статус проекта_Код статуса проекта` ASC) VISIBLE,
  CONSTRAINT `fk_Проект_Статус проекта1`
    FOREIGN KEY (`Статус проекта_Код статуса проекта`)
    REFERENCES `mydb`.`Статус проекта` (`Код статуса проекта`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Номер телефона`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Номер телефона` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Номер телефона` (
  `Код номера телефона` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Код номера телефона`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Контакты`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Контакты` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Контакты` (
  `Код контактов` INT NOT NULL AUTO_INCREMENT,
  `Номер телефона_Код номера телефона` INT NOT NULL,
  `Почта` VARCHAR(45) NOT NULL,
  `Другое` VARCHAR(45) NULL,
  PRIMARY KEY (`Код контактов`),
  INDEX `fk_Контакты_Номер телефона1_idx` (`Номер телефона_Код номера телефона` ASC) VISIBLE,
  CONSTRAINT `fk_Контакты_Номер телефона1`
    FOREIGN KEY (`Номер телефона_Код номера телефона`)
    REFERENCES `mydb`.`Номер телефона` (`Код номера телефона`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Общая информация`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Общая информация` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Общая информация` (
  `Код общей информации` INT NOT NULL AUTO_INCREMENT,
  `Фамилия` VARCHAR(100) NOT NULL,
  `Имя` VARCHAR(100) NOT NULL,
  `Отчество` VARCHAR(100) NOT NULL,
  `Контакты_Код контактов` INT NULL,
  PRIMARY KEY (`Код общей информации`),
  INDEX `fk_Общая информация_Контакты1_idx` (`Контакты_Код контактов` ASC) VISIBLE,
  CONSTRAINT `fk_Общая информация_Контакты1`
    FOREIGN KEY (`Контакты_Код контактов`)
    REFERENCES `mydb`.`Контакты` (`Код контактов`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Пользователь`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Пользователь` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Пользователь` (
  `Код пользователя` INT NOT NULL AUTO_INCREMENT,
  `Логин` VARCHAR(45) NOT NULL,
  `Хеш пароля` VARCHAR(45) NOT NULL,
  `Общая информация_Код общей информации` INT NOT NULL,
  PRIMARY KEY (`Код пользователя`),
  INDEX `fk_Пользователь_Общая информация_idx` (`Общая информация_Код общей информации` ASC) VISIBLE,
  CONSTRAINT `fk_Пользователь_Общая информация1`
    FOREIGN KEY (`Общая информация_Код общей информации`)
    REFERENCES `mydb`.`Общая информация` (`Код общей информации`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Роль в проекте`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Роль в проекте` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Роль в проекте` (
  `Код роли` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код роли`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Состояние`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Состояние` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Состояние` (
  `Код состояния` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код состояния`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Пользователь_has_Проект`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Пользователь_has_Проект` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Пользователь_has_Проект` (
  `Пользователь_Код пользователя` INT NOT NULL,
  `Проект_Код проекта` INT NOT NULL,
  `Роль в проекте_Код роли` INT NOT NULL,
  `Состояние_Код состояния` INT NOT NULL,
  PRIMARY KEY (`Пользователь_Код пользователя`, `Проект_Код проекта`),
  INDEX `fk_Пользователь_has_Проект_Проект1_idx` (`Проект_Код проекта` ASC) VISIBLE,
  INDEX `fk_Пользователь_has_Проект_Пользов_idx` (`Пользователь_Код пользователя` ASC) VISIBLE,
  INDEX `fk_Пользователь_has_Проект_Роль в п_idx` (`Роль в проекте_Код роли` ASC) VISIBLE,
  INDEX `fk_Пользователь_has_Проект_Состоян_idx` (`Состояние_Код состояния` ASC) VISIBLE,
  CONSTRAINT `fk_Пользователь_has_Проект_Пользова1`
    FOREIGN KEY (`Пользователь_Код пользователя`)
    REFERENCES `mydb`.`Пользователь` (`Код пользователя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Пользователь_has_Проект_Проект1`
    FOREIGN KEY (`Проект_Код проекта`)
    REFERENCES `mydb`.`Проект` (`Код проекта`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Пользователь_has_Проект_Роль в пр1`
    FOREIGN KEY (`Роль в проекте_Код роли`)
    REFERENCES `mydb`.`Роль в проекте` (`Код роли`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Пользователь_has_Проект_Состояни1`
    FOREIGN KEY (`Состояние_Код состояния`)
    REFERENCES `mydb`.`Состояние` (`Код состояния`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Интерес`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Интерес` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Интерес` (
  `Код интереса` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(45) NOT NULL,
  `Количественная оценка` INT NOT NULL,
  PRIMARY KEY (`Код интереса`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Влияние`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Влияние` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Влияние` (
  `Код влияния` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(45) NOT NULL,
  `Количественная оценка` INT NOT NULL,
  PRIMARY KEY (`Код влияния`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Обязательство`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Обязательство` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Обязательство` (
  `Код обязательства` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код обязательства`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Заместитель`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Заместитель` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Заместитель` (
  `Код заместителя` INT NOT NULL AUTO_INCREMENT,
  `Общая информация_Код общей информации` INT NOT NULL,
  INDEX `fk_Заместитель_Общая информация1_idx` (`Общая информация_Код общей информации` ASC) VISIBLE,
  PRIMARY KEY (`Код заместителя`),
  CONSTRAINT `fk_Заместитель_Общая информация1`
    FOREIGN KEY (`Общая информация_Код общей информации`)
    REFERENCES `mydb`.`Общая информация` (`Код общей информации`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ответственность`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ответственность` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ответственность` (
  `Код ответственности` INT NOT NULL,
  `Значение` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код ответственности`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Заинтересованное лицо`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Заинтересованное лицо` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Заинтересованное лицо` (
  `Код заинтересованного лица` INT NOT NULL AUTO_INCREMENT,
  `Компания` VARCHAR(45) NULL,
  `Должность` VARCHAR(45) NULL,
  `Цель взаимодействия` MEDIUMTEXT NULL,
  `Имеющаяся информация` LONGTEXT NULL,
  `Приоритет удовлетворения ожиданий` INT NULL,
  `Интерес_Код интереса` INT NULL,
  `Влияние_Код влияния` INT NULL,
  `Обязательство_Код обязательства` INT NULL,
  `Заместитель_Код заместителя` INT NULL,
  `Ответственность_Код ответственности` INT NULL,
  PRIMARY KEY (`Код заинтересованного лица`),
  INDEX `fk_Заинтересованное лицо_Интерес_idx` (`Интерес_Код интереса` ASC) VISIBLE,
  INDEX `fk_Заинтересованное лицо_Влияние_idx` (`Влияние_Код влияния` ASC) VISIBLE,
  INDEX `fk_Заинтересованное лицо_Обязате_idx` (`Обязательство_Код обязательства` ASC) VISIBLE,
  INDEX `fk_Заинтересованное лицо_Замести_idx` (`Заместитель_Код заместителя` ASC) VISIBLE,
  INDEX `fk_Заинтересованное лицо_Ответст_idx` (`Ответственность_Код ответственности` ASC) VISIBLE,
  CONSTRAINT `fk_Заинтересованное лицо_Интерес1`
    FOREIGN KEY (`Интерес_Код интереса`)
    REFERENCES `mydb`.`Интерес` (`Код интереса`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Заинтересованное лицо_Влияние1`
    FOREIGN KEY (`Влияние_Код влияния`)
    REFERENCES `mydb`.`Влияние` (`Код влияния`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Заинтересованное лицо_Обязател1`
    FOREIGN KEY (`Обязательство_Код обязательства`)
    REFERENCES `mydb`.`Обязательство` (`Код обязательства`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Заинтересованное лицо_Заместит1`
    FOREIGN KEY (`Заместитель_Код заместителя`)
    REFERENCES `mydb`.`Заместитель` (`Код заместителя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Заинтересованное лицо_Ответств1`
    FOREIGN KEY (`Ответственность_Код ответственности`)
    REFERENCES `mydb`.`Ответственность` (`Код ответственности`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Способ взаимодействия`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Способ взаимодействия` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Способ взаимодействия` (
  `Код способа` INT NOT NULL AUTO_INCREMENT,
  `Значение` VARCHAR(45) NOT NULL,
  `Приоритет` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код способа`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
